config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end	
  root "posts#index"

  get '/about', to: 'pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(comment_params)

		redirect_to post_path(@post)
	end	

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end	

	private

	  def comment_params 
          params.require(:comment).permit(:name, :body)
	  end	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	before_action :find_post, only: [:show, :edit, :update]
	def index
		@posts = Post.all.order("created_at DESC")
	end
	
	def new
      @post = Post.new
	end	

	def create
		@post = Post.new(post_params)
		
		if @post.save
		  redirect_to @post
		else
		  render 'new'
		end    
	end	

	def show
		
	end	


	def edit
	end
	
	def destroy
	end

	def update
		if @post.update(post_params)
			redirect @post
		else
		    render 'edit'
		end
		     	
	end	

    private

      def find_post
      	@post = Post.find(params[:id])
      end	

      def post_params
      	params.require(:post).permit(:title, :body)
      end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">

	<div class="comment_content">
		<p class="comment_name"><em><%= comment.name %></em></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago </p>
	</div>

	<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: "button", data: {confirm: 'Are you sure?'} %></p>
	
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>

    <p>
  	  <%= f.label :name %><br>
  	  <%= f.text_field :name %>
    </p>

    <p>
    	<%= f.label :body %><br>
    	<%= f.text_area :body %>
    </p>

    <p>
    	<%= f.submit %>
    </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IProfile</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Raleway: 400, 700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="sidebar">
       <ul>
       	   <li class="category"><%= link_to "iProfile", root_path %></li>
       	   <li><%=link_to "Posts", root_path %></li>
       	   <li><%=link_to "About", about_path %></li>
       </ul>
    	<% if !user_signed_in? %>
    	  <p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
      <% end %>  
    </div>

    <div id= "main_content">
       <div id="header">
          <% if current_page?(root_path) %>
            <p>Post Feed</p>
          <% elsif current_page?(about_path)%>
             <p>My Site</p>
          <% else %>
            <%= link_to "Back to Post", root_path %>
          <% end %> 
          <% if user_signed_in? %>  
            <div class="buttons">
            	  <button class="button">
            	  	 <%= link_to "Make Post", new_post_path %>
            	  </button>

            	  <button class="button">
            	  	 <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            	  </button>
            </div>
          <% end %>  
	    </div> 

		<% flash.each do |name, msg| %>
		  <%= content_tag(:div, msg, class: "alert") %>
		<% end %>


    	<%= yield %>
    </div>

    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">

	<div id="profile_image">
		<%= image_tag "vendetta.jpeg" %>
	</div>


	<div id="content">
		<h1>This is my about page</h1>
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
	</div>
	
</div>

app/views/posts/_form.html.erb
<%= form_for :post, url: posts_path do |f| %>
	<% if @post.errors.any? %>
		<h2><%= pluralize(@post.errors.count, "error") %> prevented the post from saving</h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			  <li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :body %><br>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit post</h1>

	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
    <h2 class="title"><%= link_to post.title, post %></h2>
    <p class="body"><%= truncate(post.body, length: 100) %></p>
    <p class="date"><%= time_ago_in_words(post.created_at) %> ago</p>
  </div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>Create a post for your records</h1>

	<%= render 'form' %>
</div>

	

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class=title> Title of your post: <%= @post.title %> </h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago 
		<%= link_to 'Edit', edit_post_path(@post) %> |
		<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: "Are you sure? " } %>
	</p>

	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>
		<h3>Add a comment :</h3>
		<%= render "comments/form" %>
	</div>
</div>	